from dotenv import load_dotenv
from langchain.chat_models import init_chat_model

load_dotenv()

# temperature:  is parameter control creativity of model in range of (0-1).
# max_tokens: Define the Maximum length of response generated by the model. Also manage the API costs.
model = init_chat_model(model='google_genai:gemini-2.5-flash-lite',temperature=0 ,max_tokens=20)
response = model.invoke('what is AI? give me in paragrapah')
print(response.content)