from dotenv import load_dotenv
from moonshotai import MoonshotChat
import json
import os

load_dotenv()

# temperature:  is parameter control creativity of model in range of (0-1).
# max_tokens: Define the Maximum length of response generated by the model. Also manage the API costs.
model = MoonshotChat(
    model="kimi-k2-0905-preview",
    temperature=0.7,
    moonshot_api_key=os.getenv("MOONSHOT_API_KEY")
)

HISTORY_FILE = 'chat_history.json'

def load_chat_history():
    """Load chat history from file if it exists"""
    if os.path.exists(HISTORY_FILE):
        try:
            with open (HISTORY_FILE, 'r') as f:
                return json.load(f)
        except:
            print('Warning: Could not load chat history.Starting fresh.')
    return []


def save_chat_history(messages):
    """Save chat history to file"""
    try:
        with open(HISTORY_FILE, 'w') as f:
            json.dump(messages, f, indent=2)
    except Exception as e:
        print(f"Warning: Could not save chat history: {e}")

# Load existing chat history
messages = load_chat_history()


print('------------- Welcome to Gemini Bot ----------------')
print('------------- If you want to exit enter 0 -----------')
print(f'Loaded {len(messages)} previous messages from history.')

while True:
    prompt = input('You :  ')
    
    
    if prompt == "0":
        break
    elif prompt.lower() == 'clear':
        messages = []
        print("Chat history cleared.")
        continue
    
    messages.append({'role': "user",'content': prompt})
    response = model.invoke(messages)
    messages.append({'role': "assistant",'content': response.content})

    
    print('Bot: ',response.content)

# Save chat history before exiting
save_chat_history(messages)
print('---- Chat history saved. Exit -----')